# Acuron

In [51]:
pdf_path = "test/pdf/dc/form/acuron-label.pdf"

In [52]:
import tabula

# Read pdf into list of DataFrame
dfs = tabula.read_pdf(pdf_path, pages='all', stream=True)

In [53]:
len(dfs)

14

In [54]:
dfs[3]

        ATRAZINE  GROUP   5  HERBICIDE
0  BICYCLOPYRONE  GROUP  27  HERBICIDE
1     MESOTRIONE  GROUP  27  HERBICIDE
2  S-METOLACHLOR  GROUP  15  HERBICIDE

In [30]:
pdf_path2 = "test/pdf/dc/form/Blue_Book_2023_web.pdf"

# Bluebook

In [49]:
dfs2 = tabula.read_pdf(pdf_path2, pages='all', stream=True)

In [45]:
len(dfs2)

704

In [50]:
dfs2[201]

,Unnamed: 0,Unnamed: 1,Everest 3.0 AG/Sierra,Himalaya rate per
0,Tank mix partner,Tank mix partner rate,3.0 AG rate per acre,acre
1,MCPA (Amine/Ester 600),Up to 0.38 L/acre,NaN,NaN
2,OcTTain XL***,0.45 L/acre,NaN,NaN
3,Paradigm,10 g/acre,NaN,NaN
4,Paradigm + MCPA ester,10 g/acre + 232 mL/acre,NaN,NaN
5,Paradigm + Curtail M,10 g/acre + 600 mL/acre,NaN,NaN
6,Pardner/Brotex 240,Pardner: 0.4 L/acre. Brotex: 0.49 L/acre,NaN,NaN
7,Prestige XC,Prestige XC A: 0.17 L/acre. Prestige XC B: 0.8,NaN,NaN
8,NaN,L/acre,NaN,NaN
9,Pixxaro A,Pixxaro A: 0.125 L/acre,NaN,NaN
10,Pixxaro A+ MCPA Ester,Pixxaro A: 0.125 L/acre +,NaN,NaN
11,NaN,MCPA Ester (Pixxaro B): 0.235 L/acre,NaN,NaN
12,Pixxaro A+ Curtail M,Pixxaro A: 0.125 L/acre + Curtail M: 0.60 L/,NaN,NaN
13,NaN,acre,NaN,NaN
14,Refine SG,Refine SG: 12 g/acre.,NaN,NaN
15,Refine SG+,"Refine SG: 12 g/acre. 2,4-D: up to 0.45 L/acre",NaN,NaN
16,"2, 4-D amine/ester 500",or equivalent,NaN,NaN
17,Stellar A,0.4 L/acre,NaN,NaN
18,Target*,0.4 - 0.6 L/acre,NaN,NaN
19,Thumper/Leader,Thumper: 0.4 L/acre; Leader: 0.5 L/acre,NaN,NaN
20,Triton C**,39 g/acre,NaN,NaN
21,Trophy,Trophy A: 0.24 L/acre + Trophy B: 0.372 L/acre,NaN,NaN
22,In durum wheat,NaN,NaN,NaN
23,"2,4-D (Amine 600/Ester 700)***","Up to 0.30 L/acre. Amine, 0.26 L/acre Ester",29 - 58 mL,11.5 - 17.4 g
24,Enforcer D,0.243 - 0.486 L/acre,NaN,NaN
25,Enforcer M,0.243 - 0.5 L/acre,NaN,NaN
26,Frontline***,Frontline A: 40 mL/acre. Frontline B: 0.34 L/acre,NaN,NaN
27,Paradigm and mixes,Same rates as for spring wheat above,NaN,NaN
28,Pixxaro and mixes,Same rates as for spring wheat above,NaN,NaN
29,In winter wheat,NaN,NaN,NaN
30,"2,4-D Amine or ester",0.4 L/acre or equivalent,29 - 58 mL,NR****
31,Buctril M/Logic M,"Buctril M 0.4 L/acre, Logic M 0.5 L/acre",NaN,NaN
32,MCPA Amine or ester,0.4 L/acre or equivalent,NaN,NaN
33,Refine SG,Refine SG: 12 g/acre,NaN,NaN

In [57]:
pdf_path3 = "test/pdf/dc/form/091234-00154-20200109.pdf"

In [69]:
dfs3 = tabula.read_pdf(pdf_path3, pages='all')

Got stderr: Jul. 04, 2023 5:19:39 P.M. org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+120 (120) in font BMLPFF+SymbolMT
Jul. 04, 2023 5:19:39 P.M. org.apache.pdfbox.pdmodel.font.PDType0Font toUnicode
WARNING: No Unicode mapping for CID+131 (131) in font BMMELK+Wingdings-Regular

In [70]:
len(dfs3)

146

In [78]:
dfs3[32]

Empty DataFrame
Columns: [14 days, 14 days.1]
Index: []